### ISSUE TITLE
Issue with IE8

### ISSUE THREAD

**Issue by phino** [sa3m/leaflet-control-bing-geocoder#7]
Object doesn't support this action     Control.BingGeocoder.js, line 35 character 3

35              submit.type = 'submit';

**Comment by sa3m** [comment]
Ok, I see the problem. I'll correct it. Thanks for the feedback.

**Comment by sa3m** [comment]
Please try now to see if your problem is corrected.
I used the technique from Leaflet layers control.

**Comment by phino** [comment]
thanks, will give it a try when i get back into my office. thank you and hope for some good news!

Date: Thu, 3 Apr 2014 13:22:06 -0700

**Comment by phino** [comment]
still receive the same issue that "Object doesn't support this action / Control.BingGeocoder.js,line 35 character 3

**Comment by sa3m** [comment]
Weird... it's not the same code and still the error is at the same place. Is the code minified ?

**Comment by phino** [comment]
i apologize, I take that back, we added the new geocoder.js, :) silly mistake for not adding the newly edited version. Works just fine and perfectly now! Thank you so much

**Comment by sa3m** [comment]
No problem. I close this issue.
